### ISSUE TITLE
How to show the Calories in App?  

### ISSUE THREAD

**Issue by LtveG** [igorrendulic/food_recognition_with_calorie_mama#1]
Hi ! Your code is very useful. But it can not show the calories in my App. And I change code from JSONUtil.java.

The code are as flow:

           `JSONArray results = response.optJSONArray("results");
                  for (int i=0; i<results.length(); i++) {
                       JSONObject result = results.optJSONObject(i);

                JSONArray items = result.optJSONArray("items");
                for (int j=0; j<items.length(); j++) {
                    JSONObject item = items.optJSONObject(j);
                    list.add(createItem(item.optString("name"), ""));

                    JSONArray nutritions = item.optJSONArray("nutrition");
                    for(int z=0;z<nutritions.length(); z++){
                        JSONObject nutrition = nutritions.optJSONObject(z);
                        list.add(createItem(nutrition.optString("calories"),""));`

But it is not success, can you help me? Thanks veryvery much!!

**Comment by igorrendulic** [comment]
I've added the display of calories in the example. 

This is the modified parsing part of the calories in JSONUtil.java

```
JSONArray results = response.optJSONArray("results");
            for (int i=0; i<results.length(); i++) {
                JSONObject result = results.optJSONObject(i);
                JSONArray items = result.optJSONArray("items");
                for (int j=0; j<items.length(); j++) {
                    JSONObject item = items.optJSONObject(j);
                    String itemName = item.optString("name","");
                    JSONObject nutrition = item.optJSONObject("nutrition");
                    int calories = nutrition.optInt("calories");
                    list.add(createItem(itemName + " (" + calories + " Cal)", ""));
                }
            }
```

You can also check out this page for parsing the response json: [https://dev.caloriemama.ai/docs](https://dev.caloriemama.ai/docs)
