### ISSUE TITLE
How to show the "totalCarbs" and "calories" or more? Thank U~

### ISSUE THREAD

**Issue by LtveG** [igorrendulic/food_recognition_with_calorie_mama#2]
Your code is very useful! Thank you very very much!
But I want to show more the information about food.
I have change your code as flower:
`public class JSONUtil {

    public static List<Map<String,String>> getInitalListData() {
        List<Map<String, String>> list = new ArrayList<>();
        list.add(createItem("Food Name", "Calories","totalCarbs"));
        return list;
    }

    public static void foodJsonToList(JSONObject response, List<Map<String, String>> list) {

        list.clear();

        if (response != null) {

            JSONArray results = response.optJSONArray("results");
            for (int i=0; i<results.length(); i++) {
                JSONObject result = results.optJSONObject(i);
                JSONArray items = result.optJSONArray("items");
                for (int j=0; j<items.length(); j++) {
                    JSONObject item = items.optJSONObject(j);
                    String itemName = item.optString("name","");
                    JSONObject nutrition = item.optJSONObject("nutrition");
                    int calories = nutrition.optInt("calories");
                    int totalCarbs = nutrition.optInt("totalCarbs");
                    list.add(createItem(itemName +"(" + calories + " cal)","",""));
                    list.add(createItem(itemName +"(" + totalCarbs + " car)","",""));
                }
          }` 
private static Map<String,String> createItem(String foodName, String calories,String totalCarbs) {
        Map<String,String>  item =  new HashMap<>();
        item.put("col_1", foodName);
        item.put("col_2", calories);
        item.put("col_3", totalCarbs);
        return item;
    }
}

But it only show the calories, how should i do ? 
Thank you very much!

**Comment by ghost** [comment]
You're on the right path. You have the data. My guess is you need to create a view for the col_3.

**Comment by LtveG** [comment]
Thank you for reply me!But what’s your mean of ‘a view of col_3’?I have build a list view,but it show nothing...list.add(createItem(itemName +"(" + totalCarbs + " car)","",""));Thank you very much again!
            On 04/18/2018 18:12, Igor Rendulic wrote:You're on the right path. You have the data. My guess is you need to create a view for the col_3.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/igorrendulic/food_recognition_with_calorie_mama","title":"igorrendulic/food_recognition_with_calorie_mama","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/igorrendulic/food_recognition_with_calorie_mama"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rendulic in #2: You're on the right path. You have the data. My guess is you need to create a view for the col_3. "}],"action":{"name":"View Issue","url":"https://github.com/igorrendulic/food_recognition_with_calorie_mama/issues/2#issuecomment-382337213"}}}</scri
 pt>
</blockquote>
        </div>
    </div>
    <br/>
</body>
<script type="text/javascript" src="http://app.reserve.client.163.com/compose_main.js">

**Comment by igorrendulic** [comment]
hm. could you fire up a curl and post a response here? Just replace YOUR KEY HERE with your key and image.jpg with some image (best 544x544px). 

`curl --request POST -H "Content-Type: image/jpeg" --data-binary "@image.jpg" https://api-2445582032290.production.gw.apicast.io/v1/foodrecognition?user_key=YOUR KEY HERE`
