### ISSUE TITLE
How to add activity.? 

### ISSUE THREAD

**Issue by manjunathpm** [igorrendulic/food_recognition_with_calorie_mama#3]
How to add new activity page for this project.?

**Comment by igorrendulic** [comment]
I'm not sure what you mean.

**Comment by manjunathpm** [comment]
I want to add new activity to u r existing github project. How can I do
that..??

**Comment by igorrendulic** [comment]
1. Fork this repository
2. Create local clone of your fork
3. Configure Git to sync your for with original (this) repository

These steps are described in detail [Here](https://help.github.com/articles/fork-a-repo/)

When you're done you can open a [pull request](https://help.github.com/articles/about-pull-requests/)
